In [2]:
import cv2 as cv
import numpy as np

In [5]:
image = cv.imread("download.jpg")

In [3]:
print(image)

[[[183 137  96]
  [183 137  96]
  [183 137  96]
  ...
  [186 133 100]
  [186 133 100]
  [186 133 100]]

 [[184 138  97]
  [184 138  97]
  [184 138  97]
  ...
  [185 134 101]
  [185 134 101]
  [186 135 102]]

 [[185 138 100]
  [185 138 100]
  [185 138 100]
  ...
  [187 136 103]
  [187 136 103]
  [188 137 104]]

 ...

 [[ 87  75  65]
  [ 87  75  65]
  [ 87  75  65]
  ...
  [ 33  19   7]
  [ 33  19   7]
  [ 33  19   7]]

 [[ 86  74  64]
  [ 86  74  64]
  [ 86  74  64]
  ...
  [ 33  19   7]
  [ 33  19   7]
  [ 33  19   7]]

 [[ 92  80  70]
  [ 86  74  64]
  [ 82  70  60]
  ...
  [ 33  19   7]
  [ 33  19   7]
  [ 34  20   8]]]


In [4]:
image.shape #(height,width,channel(R,G,B))

(129, 103, 3)

In [5]:
cv.imshow("Image",image)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [6]:
corner=image[0:100,0:100]
cv.imshow("Corner",corner)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [3]:
canvas = np.zeros((300, 300, 3), dtype = "uint8" )
#RGB(255,255,255)
green = (0, 255, 0)
red = (0, 0, 255)
# blue = (255, 0, 0)
cv.line(canvas, (0,0), (300,300), green, 4)
cv.line(canvas, (0,300), (300,0), red, 4)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

-1

In [6]:
# Image Translation
# The first row of the matrix is [1,0,tx], where tx is the number of pixels we will shift the image
# Negative values of tx will shift the image to the left and positive values will shift the image
M = np.float32([[1,0,25], [0,1,50]])
# print(image.shape[0])
# print(image.shape[1])
shifted = cv.warpAffine(image, M, (image.shape[1], image.shape[0]))
cv.imshow("Shifted Down and Right", shifted)
cv.waitKey(0)

13

: 

In [10]:
# Rotation
cv.imshow("Original", image)
(h, w) = image.shape[:2]
center = (w // 2, h // 2)
M = cv.getRotationMatrix2D(center, 45, 1.0)
rotated = cv.warpAffine(image, M, (w,h))
cv.imshow("Rotated by 45 Degrees", rotated)
cv.waitKey(0)

-1

In [11]:
# Resize the image
cv.imshow("Original",image)
print(image.shape)
r = 150.0 / image.shape[1]
dim = (150, int(image.shape[0] * r))
resized = cv.resize(image, dim, interpolation = cv.INTER_AREA)
print(resized.shape)
cv.imshow("Resized (Width)",resized)
cv.waitKey(0)

(129, 103, 3)
(187, 150, 3)


-1

In [12]:
#Flipping the image
cv.imshow("Original",image)
flipped = cv.flip(image, 0)
cv.imshow("Flipped Horizontally",flipped)
cv.waitKey(0)

-1

In [15]:
#Border
cv.imshow("Original",image)
white = [255,255,255]
# Border = cv.BORDER_WRAP(image, 0)
border =cv.copyMakeBorder(image,20,20,20,20,cv.BORDER_CONSTANT,value=white)
cv.imshow("Flipped Horizontally",border)
cv.waitKey(0)

-1

In [ ]:
vid = cv.VideoCapture(0)
while(True):
    ret, frame = vid.read()
    cv.imshow('MyFace', frame)
    if cv.waitKey(1) & 0xFF == ord('a'):
        break
vid.release()
cv.destroyAllWindows()